# Generated by Django 5.2.14 on 2026-06-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='category',
            field=models.CharField(choices=[('dsa', 'DSA / Algorithm'), ('security', 'Security'), ('resource', 'Resource / Reliability'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
