# Generated by Django 5.2.14 on 2026-06-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_comment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='fixed_code_after',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='fixed_code_before',
            field=models.TextField(blank=True),
        ),
    ]
