"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!


# SECURITY WARNING: don't run with debug turned on in production!

SECRET_KEY = env('SECRET_KEY')
DEBUG = env.bool('DEBUG', default=False)
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'webhooks',
    'reviews',
    'analyzer',
    'github_client',
    'accounts',
    'encrypted_model_fields',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
                BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Where to send users after a successful login
LOGIN_REDIRECT_URL = '/dashboard/'

# Where to send users when they click logout
LOGOUT_REDIRECT_URL = '/auth/login/'

# Where to login
LOGIN_URL = '/auth/login/'

# Where to logout
LOGOUT_URL = '/auth/logout/'

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'loggers': {
        'webhooks': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'tasks': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'analyzer': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
    },
}


GITHUB_OAUTH_CLIENT_ID = env("GITHUB_CLIENT_ID")
GITHUB_OAUTH_CLIENT_SECRET = env("GITHUB_CLIENT_SECRET")

# Celery
CELERY_BROKER_URL = env('REDIS_URL')
CELERY_RESULT_BACKEND = env('REDIS_URL')
CELERY_TASK_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_IMPORTS = ('tasks.review_tasks',)

# GitHub App
GITHUB_APP_ID = env('GITHUB_APP_ID')
GITHUB_WEBHOOK_SECRET = env('GITHUB_WEBHOOK_SECRET')
GITHUB_PRIVATE_KEY_PATH = env('GITHUB_PRIVATE_KEY_PATH')

# Gemini
GEMINI_API_KEY = env('GEMINI_API_KEY')
GEMINI_MODEL = env('GEMINI_MODEL', default='gemini-1.5-flash')

# OpenAI
OPENAI_API_KEY = env('OPENAI_API_KEY', default='')
OPENAI_MODEL = env('OPENAI_MODEL', default='gpt-4o')

# OpenRouter / LLM (use django-environ so Celery workers load .env like manage.py)
OPENROUTER_API_KEY = env('OPENROUTER_API_KEY', default='')
LLM_API_KEY = env('LLM_API_KEY', default='') or OPENROUTER_API_KEY
LLM_MODEL = env('LLM_MODEL', default='meta-llama/llama-3.3-70b-instruct')
LLM_PROVIDER = env('LLM_PROVIDER', default='openrouter')
# OpenRouter site URL for HTTP-Referer (required for some routes / leaderboards)
OPENROUTER_SITE_URL = env('OPENROUTER_SITE_URL', default='http://localhost:8000')

FIELD_ENCRYPTION_KEY = env("FIELD_ENCRYPTION_KEY")