# Generated by Django 5.2.14 on 2026-05-31 20:16

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMKeyRingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_identifier', models.CharField(help_text='e.g. openrouter_acc1, gemini_acc2', max_length=100)),
                ('provider', models.CharField(choices=[('openrouter', 'Tier 1: OpenRouter'), ('openai', 'Tier 2: OpenAI'), ('gemini', 'Tier 3: Gemini')], max_length=30)),
                ('key_value', encrypted_model_fields.fields.EncryptedCharField()),
                ('model_override', models.CharField(blank=True, help_text='Optional: override default model for this key', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('total_calls_handled', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['provider', 'total_calls_handled'],
            },
        ),
    ]
