# Generated by Django 5.2.14 on 2026-06-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmkeyringslot',
            name='account_identifier',
            field=models.CharField(help_text='e.g. gemini_acc1, openrouter_acc1, openai_acc2', max_length=100),
        ),
        migrations.AlterField(
            model_name='llmkeyringslot',
            name='model_override',
            field=models.CharField(blank=True, help_text='Optional: override default model string profile for this key', max_length=100),
        ),
        migrations.AlterField(
            model_name='llmkeyringslot',
            name='provider',
            field=models.CharField(choices=[('gemini', 'Tier 1: Gemini'), ('openrouter', 'Tier 2: OpenRouter'), ('openai', 'Tier 3: OpenAI')], max_length=30),
        ),
    ]
