# Generated by Django 5.2.14 on 2026-06-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_alter_llmkeyringslot_account_identifier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='llmkeyringslot',
            options={'ordering': ['total_calls_handled']},
        ),
        migrations.AlterField(
            model_name='llmkeyringslot',
            name='provider',
            field=models.CharField(choices=[('openrouter', 'OpenRouter'), ('gemini', 'Gemini'), ('openai', 'OpenAI')], max_length=30),
        ),
    ]
